# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_optimization.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Optimization(object):
    def setupUi(self, Optimization):
        Optimization.setObjectName("Optimization")
        Optimization.resize(565, 663)
        self.verticalLayout = QtWidgets.QVBoxLayout(Optimization)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Optimization)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.data_table = QtWidgets.QTableWidget(Optimization)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.data_table.setFont(font)
        self.data_table.setObjectName("data_table")
        self.data_table.setColumnCount(0)
        self.data_table.setRowCount(0)
        self.verticalLayout.addWidget(self.data_table)
        self.frame = QtWidgets.QFrame(Optimization)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.frame.setFont(font)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.export_csv = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.export_csv.setFont(font)
        self.export_csv.setObjectName("export_csv")
        self.horizontalLayout.addWidget(self.export_csv)
        self.copy_values = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.copy_values.setFont(font)
        self.copy_values.setObjectName("copy_values")
        self.horizontalLayout.addWidget(self.copy_values)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Optimization)
        QtCore.QMetaObject.connectSlotsByName(Optimization)

    def retranslateUi(self, Optimization):
        _translate = QtCore.QCoreApplication.translate
        Optimization.setWindowTitle(_translate("Optimization", "Dialog"))
        self.label.setText(_translate("Optimization", "Molcule Optimization Steps"))
        self.export_csv.setText(_translate("Optimization", "Export to CSV"))
        self.copy_values.setText(_translate("Optimization", "Copy Values"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Optimization = QtWidgets.QDialog()
    ui = Ui_Optimization()
    ui.setupUi(Optimization)
    Optimization.show()
    sys.exit(app.exec_())
