# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_splash.ui'
#
# Created by: PySide2 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(629, 277)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainFrame = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.mainFrame.setFont(font)
        self.mainFrame.setStyleSheet("QFrame#mainFrame{\n"
"    background-color: rgb(233, 238, 250);\n"
"    border-radius: 10px;\n"
"}\n"
"QProgressBar#progress{\n"
"    background-color: rgb(92, 131, 164);\n"
"    color: rgb(238, 238, 236);\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar#progress:chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494318, x2:0.856, y2:0.511364, stop:0 rgba(114, 159, 207, 255), stop:1 rgba(32, 81, 153, 255));\n"
"}\n"
"\n"
"QLabel#loader{\n"
"    color: rgb(32, 74, 135);\n"
"    text-align: center;\n"
"}\n"
"QLabel#credit{\n"
"    \n"
"}")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_3 = QtWidgets.QLabel(self.mainFrame)
        self.title_3.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.title_3.setFont(font)
        self.title_3.setText("")
        self.title_3.setPixmap(QtGui.QPixmap("ui/../icons/spectrum-icon.png"))
        self.title_3.setObjectName("title_3")
        self.horizontalLayout.addWidget(self.title_3)
        self.title = QtWidgets.QLabel(self.mainFrame)
        self.title.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        self.title_2 = QtWidgets.QLabel(self.mainFrame)
        self.title_2.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.title_2.setFont(font)
        self.title_2.setObjectName("title_2")
        self.horizontalLayout.addWidget(self.title_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.loader = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(13)
        self.loader.setFont(font)
        self.loader.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.loader.setObjectName("loader")
        self.verticalLayout_2.addWidget(self.loader)
        self.progress = QtWidgets.QProgressBar(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.progress.setFont(font)
        self.progress.setProperty("value", 24)
        self.progress.setObjectName("progress")
        self.verticalLayout_2.addWidget(self.progress)
        self.label_3 = QtWidgets.QLabel(self.mainFrame)
        self.label_3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.credit = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.credit.setFont(font)
        self.credit.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.credit.setObjectName("credit")
        self.verticalLayout_2.addWidget(self.credit)
        self.verticalLayout.addWidget(self.mainFrame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:36pt; font-weight:600; color:#204a87;\">GSA </span></p></body></html>"))
        self.title_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#3465a4;\">Gaussian Spectrum Analyzer</span></p></body></html>"))
        self.loader.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#204a87;\">LOADING DATABASE</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#204a87;\">loading...</span></p></body></html>"))
        self.credit.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#3465a4;\">Created By</span>: <span style=\" font-weight:600; color:#204a87;\">Moaz Mohammed El-Essawey</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
